# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/eyre921/default-dev-env:latest
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      imports:
        - https://cnb.cool/eyre921/secret/-/blob/main/edgeone-pages-env.yml
        - https://cnb.cool/eyre921/secret/-/blob/main/dk.yml
      stages:
        - name: start 1P
          script: 1pctl start all
        - name: install env
          script: pnpm install && pnpm build 
        - name: droid-key
          script: dk add $FACTORY_API_KEY

# .cnb.yml

master:
  push:
    - &docs_deploy_pipeline
      imports:
        - https://cnb.cool/eyre921/secret/-/blob/main/edgeone-pages-env.yml
      runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/eyre921/default-dev-env:latest
      env:
        EDGEONE_PROJECT_NAME: vibe-vibe-production
      
      stages:
        - &docs_build_stage
          name: Build Site
          script:
            - pnpm install --frozen-lockfile
            - pnpm build
        - &edgeone_deploy_stage
          name: Deploy to EdgeOne Pages
          script:
            - npx -y edgeone pages deploy ./docs/.vitepress/dist -n $EDGEONE_PROJECT_NAME --force -t $EDGEONE_API_TOKEN

develop:
  pull_request.merged:
    - <<: *docs_deploy_pipeline
      env:
        EDGEONE_PROJECT_NAME: vibe-vibe-develop
      
      stages:
        - *docs_build_stage
        - *edgeone_deploy_stage
